In [1]:
# Importing libraries
import numpy as np

In [2]:
# Loading data
train, test = "data/df_train.csv", "data/df_test.csv"
train = np.loadtxt(train, skiprows=1, delimiter=",")
test = np.loadtxt(test, skiprows=1, delimiter=",")
_labels = set(train[:,-1])

# CART Cost and Gini functions

In [3]:
def Gini(left_data, right_data, labels):
    # This function calculates the total CART cost function for a particular left-right split (p. 221 in Hands-on ML).
    # For the left and right subset, we compute the Gini index (the impurity), multiply it by the fraction of instances
    # in that particular subset, and then sum the two values together.
    
        # Creates a list of the classes
        classes = labels
        
        # N amount of instances in parent node
        N = len(left_data[:,-1]) + len(right_data[:,-1])
    
        # Puts the two subsets in a list
        datas = [left_data, right_data]
        
        # Initialize the CART cost function
        G = 0
        
        # Iterate over the two subsets
        for data in datas:
            # Initializes impurity (gini index) for subset
            impurity = 0
            # M amount of instances in this subset
            M = len(data[:,-1])

            # Computes the impurity for the subset. Formula: G_index = sum(pk * (1 – pk))
            # Note: The sum is over each class and pk is the fraction of that class in the subset
            for i in classes:
                # Finds the fraction of instances of the particular class in the subset
                x = data[data[:,-1] == i][:,-1]
                pk = len(x) / M
                impurity += pk * (1 - pk)
            
            # Adds fraction of nodes in subset multiplied by the subset impurity to the final CART cost function
            G += M/N * impurity
        return G
            
        

In [4]:
def testGini(data, min_sample_leaf):
    if len(data[:,-1]) <= min_sample_leaf:
        return False
    
    # Initialize the minimum gini index & the row and column indexes which achieved that value
    minimum_gini = 2
    minimum_gini_indexes = [None, None]

    # Iterates over each feature in the data (each column except last)
    for i in range(len(data[0,:-1])):

        # Iterates over each row & tries to split the data on that particular value
        # Tests Gini index on that split and compares it to minimum_gini
        for j in range(len(data[:,i])):
            
            # This skips the largest value in the feature, so we get N-1 splits
            # Avoids zero division in Gini function
            if data[j,i] == np.amax(data[:,i]):
                continue

            # Creates a mask that selects all values
            # that are less than or equal to the particular row and column value
            # We test if this is the best split
            mask = data[:,i] <= data[j,i]

            # Makes the left-right split in data that we want to test
            left_data = data[:,:][mask]
            right_data = data[:,:][~mask]

            """
            print("Searching for values smaller than or equal to", j)
            print(train[:,i][mask])
            print("-")
            print("And here's all the column for that condition:")
            print(train[:,:][mask])
            print("-")"""
            
            """
            print("\n")
            print("Finding cost function of data:")
            print("The split condition")
            print(train[j,i])
            print("left")
            print(left_data)
            print("right")
            print(right_data)"""
            
            """# Stopping criterion
            # The first is the minimum number of elements in the leaf node & the second is the gini minimum
            stopping_criterion = [4, 0.1]
            
            # Check for first criterion
            if len(data_masked) >= stopping_criterion[0]:"""
            
            # Tests the Cost Function for the particular split
            G = Gini(left_data, right_data,_labels)
            #print(G)
                
            # Checks if new gini minimum   ////  & second criterion ////
            # If true, changes minimum_gini and minimum_gini_indexes
            if G < minimum_gini: # and G >= stopping_criterion[1]:
                #print("True")
                #print(minimum_gini)
                minimum_gini = G
                #print(minimum_gini)
                minimum_gini_indexes = [j, i]
        
    # returns the minimum gini index & the corresponding indexes
    return minimum_gini, minimum_gini_indexes

In [5]:
# Testing field -- Output of Gini function
testGini(train, 5)

(0.6199065196548418, [47, 7])

In [6]:
# Testing field
print(train[47,7])
print(sorted(train[:,7]))

0.27
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.06, 0.09, 0.14, 0.15, 0.27, 0.53, 0.54, 0.56, 0.61, 0.64, 0.66, 0.69, 1.06, 1.19, 1.38, 1.55, 1.57, 1.57, 1.59, 1.63, 1.67, 1.68, 1.71, 2.2, 2.88, 3.15]


# Decision Tree Algorithm

#### DT and Node classes that call functions above

In [7]:
class Node():
    # Initializes new node
    def __init__(self, data, min_sample_split, max_depth, node_depth):
        # Initializes attributes
        self.data = data # subset of data on Node
        self.left = None
        self.right = None
        self.class_predict = None
        self.min_sample_split = min_sample_split # Stop condition
        self.max_depth = max_depth
        self.node_depth = node_depth
        
        #print("Depth of node: ", self.node_depth)
        
        ### STOP CONDITIONS - BECOMES LEAF NODE ###
        # & then decide class (based on most frequent class in Node) 
        # If Node data length smaller than minimum sample for a leaf OR if node_depth equal to max_depth

        if (len(self.data[:,-1]) <= self.min_sample_split) or (self.node_depth == self.max_depth) or (len(set(self.data[:,-1])) == 1):
            self.counts = np.bincount(self.data[:,-1].astype(int))
            self.class_predict = np.argmax(self.counts)
            
            #print("Node ready to predict! Class:", self.class_predict)
        
        else:
            self.minimum_gini, self.minimum_gini_indexes = testGini(data, self.min_sample_split)
            self.j, self.i = self.minimum_gini_indexes[0], self.minimum_gini_indexes[1]
            self.split_value = self.data[self.j, self.i]
            self.mask = self.data[:,self.i] <= self.split_value
            self.left_data, self.right_data = self.data[self.mask], self.data[~self.mask]
            
            """print("Left data:")
            print(self.left_data)
            print("Right data:")
            print(self.right_data)
            print("\n")"""
            
        #print("true")

class DecisionTree():
    def __init__(self, min_sample_split, max_depth): 
        # Initializes empty Decision Tree
        self.root = None  # root of DT
        self.count = 0
        self.tree_depth = []
        
        # Pre-pruning
        self.min_sample_split = min_sample_split  
        self.max_depth = max_depth
    
    def insert(self, data):
        # Inserts root node or calls other function
        if not self.root:
            self.root = Node(data, self.min_sample_split, self.max_depth, 0)
            
            """print("Root data, left - right")
            print(self.root.left_data[:,-1])
            print("-")
            print(self.root.right_data[:,-1])
            print("\n")"""
            
            self.insertNode(self.root.left_data, self.root)
            self.insertNode(self.root.right_data, self.root)
        else:
            self.insertNode(data, self.root)
            
    def insertNode(self, data, node):
        #print("Inserting node", self.count)
        #print(self.depth())
        self.count += 1
        
        #print("--- TESTING ---")
        #print(node.data[:,-1])
        #print(node.class_predict)
        """print(node.left)
        print(node.right)
        print("--- ---- ---")"""
        
        """if node.class_predict:
            print("BREAAAAK")"""
        
        # Break condition if leaf node
        #if not node.class_predict:
        #if node.class_predict == -1:
        if node.class_predict is None:
            
            if node.left:
                self.insertNode(data, node.left)
            else:
                node.left = Node(node.left_data, self.min_sample_split, self.max_depth, node.node_depth+1)
                try:
                    self.insertNode(node.left.left_data, self.root) #node.left) #self.root)
                except:
                    pass
                try:
                    self.insertNode(node.left.right_data, self.root) #node.right) #self.root)
                except:
                    pass
                    
            if node.right:
                self.insertNode(data, node.right)
            else:
                node.right = Node(node.right_data, self.min_sample_split, self.max_depth, node.node_depth+1)
                try:
                    self.insertNode(node.right.left_data, self.root) #node.left) #self.root)
                except:
                    pass
                try:
                    self.insertNode(node.right.right_data, self.root) #node.right) #self.root)
                except:
                    pass
        else:
            self.tree_depth.append(node.node_depth)
            
                
    def fit(self, data):
        self.insert(data)
        
    def traverse(self, row, node):
        #print(row)
        #print(node.i)
        #if node.class_predict:
        if node.class_predict is not None:
            return node.class_predict
        else:
            if row[node.i] <= node.split_value:
                #print("value", row[node.i], "lower or equal to", node.split_value)
                return self.traverse(row, node.left)
            else:
                return self.traverse(row, node.right)
                #print("value", row[node.i], "higher than", node.split_value)
    
    
    def predict(self, data):
        predictions = []
        
        #print(len(np.shape(data)))
        
        if len(np.shape(data)) > 1:
            for row in data:
                node = self.root
                predictions.append(self.traverse(row, node))
            return np.array(predictions)
        else:
            node = self.root
            predictions.append(self.traverse(data, node))
            return np.array(predictions)

    def depth(self):
        return max(self.tree_depth)
    
    # Old depth function
    """def depth(self):
        node = self.root
        #print(node)
        return self.depthRecursive(node, depth=0)
        
    def depthRecursive(self, node, depth):
        if node.class_predict is None:
            depth += 1
            if node.left:
                return self.depthRecursive(node.left, depth)
            if node.right:
                return self.depthRecursive(node.right, depth)
        else:
            return depth """      

# Performance Metrics Functions

In [8]:
import numpy as np

# Function that computes a confusion matrix which is used to compute the below functions
def cm_maker(y, ypred, n_classes):
    
    low = [1, 2, 3]
    high = [5, 6, 7]
    
    cm = np.zeros((n_classes, n_classes))
    
    for i, j in zip(ypred, y):
        
        if i in low:
            i = i - 1
        if i in high:
            i = i - 2
            
        if j in low:
            j = j - 1
        if j in high:
            j = j - 2
            
        cm[int(i), int(j)] += 1
        
    return cm


# Function computes precision score
def preci(cm, c):
    
    if sum(cm[c,:]) == 0:
        return 0
    else:
        return cm[c,c]/sum(cm[c,:])


# Function computes recall score
def recall(cm, c):
    
    return cm[c,c]/sum(cm[:,c])


# Function computes f1-score
def f1(cm, c):
    if (preci(cm,c) + recall(cm,c)) == 0:
        return 0
    else: 
        return 2 * (preci(cm,c) * recall(cm,c)) / (preci(cm,c) + recall(cm,c))
    

# Function computes weighted f1-score
def weighted_f1(cm, n_classes):
    co_su=cm.sum(axis=0)
    n=cm.sum()
    
    weighted_f1_sum = 0
    
    for c in range(n_classes):
        if co_su[c] != 0:
            weighted_f1_sum += f1(cm, c) * co_su[c] / n

    return round(weighted_f1_sum, 3)
        

# Function computes macro f1-score
def macro_f1(cm, n_classes):
    
    f1_sum = 0
    
    for i in range(n_classes):
        f1_sum += f1(cm, i)
    
    return round(f1_sum / n_classes, 3)


# Function to get accuracy
def accuracy(test_y, ypred):
    
    # Count of times where true labels equal predictions
    true_positives = 0
    for i in range(len(test_y)):
        if test_y[i] == ypred[i]:
            true_positives += 1
    
    return true_positives / len(test_y)


def accuracy_(y, ypred):
    y, ypred = np.array(y), np.array(ypred)
    accuracy = np.sum(y == ypred) / len(y)
    return accuracy

# Combines functions above for a coherent performance report
def performance_report(test_y, ypred, n_classes):
    
    class_labels = [1, 2, 3, 5, 6, 7]
    cm = cm_maker(test_y, ypred, n_classes)
    
    print('\nConfusion matrix for prediction:\n', cm)
    print('\n\nAccuracy for prediction:\n', accuracy(test_y, ypred))
    
    print('\n\nMetrics for classes')
    print('_______________________________________________________________________________')
    print('Class\t|\tPrecision\t|\tRecall\t\t|\tF1 Score')
    print('_______________________________________________________________________________')
    
    for i in range(n_classes):
        
        print('\nClass', class_labels[i],'|\t',round(preci(cm, i), 3),'\t\t|\t',round(recall(cm, i), 3),'\t\t|\t',round(f1(cm, i), 3))
    
    print('\n\nWeighted F1 score:\n', weighted_f1(cm, n_classes))
    print('\nMacro F1 score:\n', macro_f1(cm, n_classes))

# Warm-up DT algorithm training (without cross-validation)

In [9]:
# Initialising the model
# The input variable (min_sample_leaf) decides the minimum size of leaf nodes
DT = DecisionTree(8, 10)

In [10]:
# Fitting the model to train data
DT.fit(train)

In [11]:
DT.depth()

9

In [12]:
# Predicting test data & outputs array of predictions
y_predicted = DT.predict(test[:,:-1])

In [13]:
# Array of actual values
y_actual = test[:,-1]

In [14]:
cm_maker(y_actual, y_predicted,len(np.unique(train[:,-1]))).T

array([[17.,  2.,  2.,  0.,  0.,  0.],
       [ 5., 15.,  1.,  1.,  1.,  0.],
       [ 1.,  2.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  2.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  8.]])

In [15]:
accuracy_(y_actual, y_predicted)

0.7384615384615385

# Testing SKLearn DT - just for comparison

In [16]:
### TESTING SKLEARN ####
from sklearn.tree import DecisionTreeClassifier
# Hyperparamters: min_sample_split=8, max_depth=10
clf = DecisionTreeClassifier(max_depth=10, min_samples_split=8)#, random_state=0)
clf.fit(train[:,:-1], train[:,-1])
sk_y_predicted = clf.predict(test[:,:-1])
accuracy_(y_actual, sk_y_predicted)

0.7076923076923077

# Cross validation - Multiclass Classification

In [17]:
import tools.utils as sp

In [18]:
sets = sp.n_folder(5,train,shuffle_before_split=True)

In [19]:
cross_accuracies = []

for i in range(1,10):
    for j in range(1,10):
        
        cv_acc = []
        for idx, item in enumerate(sets):

            cross_test, cross_train = item  
            cross_DT = DecisionTree(i, j) 
            cross_DT.fit(cross_train)
            cross_y_predicted = cross_DT.predict(cross_test[:,:-1])
            cross_y_actual = cross_test[:,-1]
            
            cross_accuracy = accuracy_(cross_y_actual, cross_y_predicted)
            cv_acc.append(cross_accuracy)
            
        cross_accuracies.append([i, j, np.mean(cv_acc)])

    
a = np.array(cross_accuracies)
sorted_a = a[np.argsort(a[:, -1])]

print(sorted_a)

[[1.         1.         0.46896552]
 [4.         1.         0.46896552]
 [6.         1.         0.46896552]
 [7.         1.         0.46896552]
 [3.         1.         0.46896552]
 [8.         1.         0.46896552]
 [2.         1.         0.46896552]
 [9.         1.         0.46896552]
 [5.         1.         0.46896552]
 [2.         2.         0.57241379]
 [4.         2.         0.57241379]
 [8.         2.         0.57241379]
 [1.         2.         0.57241379]
 [5.         2.         0.57241379]
 [3.         2.         0.57241379]
 [7.         2.         0.57241379]
 [9.         2.         0.57241379]
 [6.         2.         0.57241379]
 [9.         4.         0.59310345]
 [9.         6.         0.59310345]
 [9.         5.         0.6       ]
 [5.         4.         0.60689655]
 [4.         4.         0.60689655]
 [6.         4.         0.60689655]
 [3.         4.         0.60689655]
 [1.         4.         0.60689655]
 [2.         4.         0.60689655]
 [7.         4.         0.60

From the cross validation test we can see that <b>min_sample_split=4</b> and <b>max_depth=5</b> yielded the best results for multiclass with an <b>accuracy of ~0.62</b>

# Final evaluation - Multiclass Classification

In [20]:
DT = DecisionTree(4, 5)
DT.fit(train)
y_predicted = DT.predict(test[:,:-1])
y_actual = test[:,-1]
        
performance_report(y_actual, y_predicted, n_classes=6)


Confusion matrix for prediction:
 [[18.  1.  1.  0.  1.  0.]
 [ 1. 18.  2.  0.  0.  0.]
 [ 2.  1.  2.  0.  0.  1.]
 [ 0.  2.  0.  4.  0.  0.]
 [ 0.  1.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.  8.]]


Accuracy for prediction:
 0.8


Metrics for classes
_______________________________________________________________________________
Class	|	Precision	|	Recall		|	F1 Score
_______________________________________________________________________________

Class 1 |	 0.857 		|	 0.857 		|	 0.857

Class 2 |	 0.857 		|	 0.783 		|	 0.818

Class 3 |	 0.333 		|	 0.4 		|	 0.364

Class 5 |	 0.667 		|	 1.0 		|	 0.8

Class 6 |	 0.667 		|	 0.667 		|	 0.667

Class 7 |	 1.0 		|	 0.889 		|	 0.941


Weighted F1 score:
 0.805

Macro F1 score:
 0.741


# Cross validation - Binary Classification

In [21]:
# Splitting data to Window (1) and non-Window (0):

# Loading data
train2, test2 = "data/df_train.csv", "data/df_test.csv"
train2 = np.loadtxt(train2, skiprows=1, delimiter=",")
test2 = np.loadtxt(test2, skiprows=1, delimiter=",")

for idx,i in enumerate(train2):
    if i[-1] == 1 or i[-1] == 2 or i[-1] == 3:
        train2[idx,-1] = 1
    else:
        train2[idx,-1] = 2
        
for idx,i in enumerate(test2):
    if i[-1] == 1 or i[-1] == 2 or i[-1] == 3:
        test2[idx,-1] = 1
    else:
        test2[idx,-1] = 2

In [22]:
sets = sp.n_folder(5,train2,shuffle_before_split=True)

In [23]:
bi_cross_accuracies = []

for i in range(1,10):
    for j in range(1,10):
        
        cv_acc = []
        for idx, item in enumerate(sets):

            cross_test, cross_train = item  
            cross_DT = DecisionTree(i, j) 
            cross_DT.fit(cross_train)
            cross_y_predicted = cross_DT.predict(cross_test[:,:-1])
            cross_y_actual = cross_test[:,-1]
            
            cross_accuracy = accuracy_(cross_y_actual, cross_y_predicted)
            cv_acc.append(cross_accuracy)
            
        bi_cross_accuracies.append([i, j, np.mean(cv_acc)])

    
a = np.array(cross_accuracies)
sorted_a = a[np.argsort(a[:, -1])]

print(sorted_a)

[[1.         1.         0.46896552]
 [4.         1.         0.46896552]
 [6.         1.         0.46896552]
 [7.         1.         0.46896552]
 [3.         1.         0.46896552]
 [8.         1.         0.46896552]
 [2.         1.         0.46896552]
 [9.         1.         0.46896552]
 [5.         1.         0.46896552]
 [2.         2.         0.57241379]
 [4.         2.         0.57241379]
 [8.         2.         0.57241379]
 [1.         2.         0.57241379]
 [5.         2.         0.57241379]
 [3.         2.         0.57241379]
 [7.         2.         0.57241379]
 [9.         2.         0.57241379]
 [6.         2.         0.57241379]
 [9.         4.         0.59310345]
 [9.         6.         0.59310345]
 [9.         5.         0.6       ]
 [5.         4.         0.60689655]
 [4.         4.         0.60689655]
 [6.         4.         0.60689655]
 [3.         4.         0.60689655]
 [1.         4.         0.60689655]
 [2.         4.         0.60689655]
 [7.         4.         0.60

From the cross validation test we can see that <b>min_sample_split=4</b> and <b>max_depth=5</b> yielded the best results for binary classification with an <b>accuracy of ~0.62</b>

# Final evaluation - Binary Classification

In [24]:
bi_DT = DecisionTree(4, 5)
bi_DT.fit(train2)
bi_y_predicted = bi_DT.predict(test2[:,:-1])
bi_y_actual = test2[:,-1]
        
performance_report(bi_y_actual.astype(int), bi_y_predicted, n_classes=2)


Confusion matrix for prediction:
 [[47.  1.]
 [ 2. 15.]]


Accuracy for prediction:
 0.9538461538461539


Metrics for classes
_______________________________________________________________________________
Class	|	Precision	|	Recall		|	F1 Score
_______________________________________________________________________________

Class 1 |	 0.979 		|	 0.959 		|	 0.969

Class 2 |	 0.882 		|	 0.938 		|	 0.909


Weighted F1 score:
 0.954

Macro F1 score:
 0.939
